{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yeshuihan",
    "module": "reinforce",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "reinforce-1.0.jar",
          "url": "reinforce-1.0.jar",
          "size": 5649,
          "sha512": "1a90fcf9718ef8e045a1ec3deb4ac57243a7294813c1ca88fb7254c113e08bca629d0fdad57d4d56f25a562571c233a1be8cb49ec9db08fb42cfde0d537209f9",
          "sha256": "525eb2067692fb00206996f1afe891b43c51bae12304b310d32b075f5489e596",
          "sha1": "84ff05abb9a360099bcc99a946f0696adced09d2",
          "md5": "b8264f8a310b9104b94ca55ad5ef5fb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "reinforce-1.0.jar",
          "url": "reinforce-1.0.jar",
          "size": 5649,
          "sha512": "1a90fcf9718ef8e045a1ec3deb4ac57243a7294813c1ca88fb7254c113e08bca629d0fdad57d4d56f25a562571c233a1be8cb49ec9db08fb42cfde0d537209f9",
          "sha256": "525eb2067692fb00206996f1afe891b43c51bae12304b310d32b075f5489e596",
          "sha1": "84ff05abb9a360099bcc99a946f0696adced09d2",
          "md5": "b8264f8a310b9104b94ca55ad5ef5fb3"
        }
      ]
    }
  ]
}
