{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yeshuihan",
    "module": "reinforce",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "reinforce-1.0.jar",
          "url": "reinforce-1.0.jar",
          "size": 22973,
          "sha512": "529c407154d37d7ef8f841fc62e2c720f807cf4ea32fadc5a6f6e983cb90edbcb508c696a7e5199a9dcf3a12f3cb8e45dcb8600c8a9a2a068578d40467819d8b",
          "sha256": "de50f44b9cfad8634cffd379897c6e3a6146e1a81c1b99a178a27f34c7f8bca1",
          "sha1": "3a3ab8c9fa6259a3708f326455e516303874e3e3",
          "md5": "a71e50d81333bbf37ddb66e195e37f5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "HotFixStudy",
          "module": "Common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "reinforce-1.0.jar",
          "url": "reinforce-1.0.jar",
          "size": 22973,
          "sha512": "529c407154d37d7ef8f841fc62e2c720f807cf4ea32fadc5a6f6e983cb90edbcb508c696a7e5199a9dcf3a12f3cb8e45dcb8600c8a9a2a068578d40467819d8b",
          "sha256": "de50f44b9cfad8634cffd379897c6e3a6146e1a81c1b99a178a27f34c7f8bca1",
          "sha1": "3a3ab8c9fa6259a3708f326455e516303874e3e3",
          "md5": "a71e50d81333bbf37ddb66e195e37f5d"
        }
      ]
    }
  ]
}
