{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yeshuihan",
    "module": "reinforceplugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "reinforceplugin-1.0.jar",
          "url": "reinforceplugin-1.0.jar",
          "size": 11246,
          "sha512": "17304f66244d2a9a742326c1a35679bd8aff0a6f8ce0c44143eb497e079eabb1b1f21b82173cdc2ce35f3224b502c16af30c6bb3c0845d938c623b9b5781125b",
          "sha256": "d08d303286c545c64f50ebe969fb1858c936960f1e2dbc9a59c58813e05de618",
          "sha1": "f93c6fc799e31f0e8638e01b9e41701f394bc61c",
          "md5": "f4943d496a50b41011a6f2e27a4c651b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.yeshuihan",
          "module": "reinforce",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "reinforceplugin-1.0.jar",
          "url": "reinforceplugin-1.0.jar",
          "size": 11246,
          "sha512": "17304f66244d2a9a742326c1a35679bd8aff0a6f8ce0c44143eb497e079eabb1b1f21b82173cdc2ce35f3224b502c16af30c6bb3c0845d938c623b9b5781125b",
          "sha256": "d08d303286c545c64f50ebe969fb1858c936960f1e2dbc9a59c58813e05de618",
          "sha1": "f93c6fc799e31f0e8638e01b9e41701f394bc61c",
          "md5": "f4943d496a50b41011a6f2e27a4c651b"
        }
      ]
    }
  ]
}
