{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yeshuihan.hotfixstudy",
    "module": "reinforceplugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "reinforceplugin-1.0.jar",
          "url": "reinforceplugin-1.0.jar",
          "size": 14508,
          "sha512": "3ce765163b97f3c2061520b57e06db90b664a1cca93be6d25861bfb50892e186b9524d64a9065623df44feaa902d8e2ee8d6dbebe307cc7d8afe55e4c2a271e9",
          "sha256": "2bd332be8091278d02f7e907ecb4a77da2096cbffa487478576f3581d37f17bd",
          "sha1": "f7369190f8e85d64fd1f97892d6ecb49bc30478b",
          "md5": "046aa6cfdc73c72b4895c03c84d1407e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.yeshuihan.hotfixstudy",
          "module": "reinforce",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "reinforceplugin-1.0.jar",
          "url": "reinforceplugin-1.0.jar",
          "size": 14508,
          "sha512": "3ce765163b97f3c2061520b57e06db90b664a1cca93be6d25861bfb50892e186b9524d64a9065623df44feaa902d8e2ee8d6dbebe307cc7d8afe55e4c2a271e9",
          "sha256": "2bd332be8091278d02f7e907ecb4a77da2096cbffa487478576f3581d37f17bd",
          "sha1": "f7369190f8e85d64fd1f97892d6ecb49bc30478b",
          "md5": "046aa6cfdc73c72b4895c03c84d1407e"
        }
      ]
    }
  ]
}
