{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yeshuihan.hotfixstudy",
    "module": "runtimeprintplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "runtimeprintplugin-1.0.0.jar",
          "url": "runtimeprintplugin-1.0.0.jar",
          "size": 20626,
          "sha512": "09ed198e2f0db1190bef7b365dbaf4dbc950d91114baab8755bc7a730281e21512a5f7f2a9d72a04bbd48a1844d9bb4bb7201f675efc84802f5d884548da490c",
          "sha256": "725dee30f9671245cb3075e7607f4866b30504c6789661afda5d2b9bad7fba26",
          "sha1": "5e00b080536ed20cd4d9d42504d6456d8de80373",
          "md5": "8e0d471ceb0996b6c67d14389f6d1eb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.yeshuihan.hotfixstudy",
          "module": "runtimeprint",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "runtimeprintplugin-1.0.0.jar",
          "url": "runtimeprintplugin-1.0.0.jar",
          "size": 20626,
          "sha512": "09ed198e2f0db1190bef7b365dbaf4dbc950d91114baab8755bc7a730281e21512a5f7f2a9d72a04bbd48a1844d9bb4bb7201f675efc84802f5d884548da490c",
          "sha256": "725dee30f9671245cb3075e7607f4866b30504c6789661afda5d2b9bad7fba26",
          "sha1": "5e00b080536ed20cd4d9d42504d6456d8de80373",
          "md5": "8e0d471ceb0996b6c67d14389f6d1eb8"
        }
      ]
    }
  ]
}
